// <auto-generated />
using ExplorerApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExplorerApi.Migrations
{
    [DbContext(typeof(ExplorerApiContext))]
    [Migration("20220831023139_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ExplorerApi.Models.Place", b =>
                {
                    b.Property<int>("PlaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Country")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("PlaceId");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            PlaceId = 1,
                            City = "Paris",
                            Country = "France",
                            Name = "Adrienne",
                            Rating = 5
                        },
                        new
                        {
                            PlaceId = 2,
                            City = "Portland",
                            Country = "USA",
                            Name = "Royal",
                            Rating = 5
                        },
                        new
                        {
                            PlaceId = 3,
                            City = "El Salvador",
                            Country = "South America",
                            Name = "Pancake",
                            Rating = 3
                        },
                        new
                        {
                            PlaceId = 4,
                            City = "Madrid",
                            Country = "Spain",
                            Name = "Adrienne",
                            Rating = 4
                        },
                        new
                        {
                            PlaceId = 5,
                            City = "Milan",
                            Country = "Italy",
                            Name = "Pancake",
                            Rating = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
